# Site settings
title: 夏敏的博客
SEOTitle: 夏敏的博客 | Anderson's Blog
header-img: img/bg-google.png
email: jerey_jobs@qq.com
description: "这里是夏敏的个人博客，希望能与你一同进步。"
keyword: "夏敏, Android, Anderson, Jerey_Jobs, Anderson大码渣, 博客, 个人网站, 互联网"
url: "https://jerey-jobs.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     3931239166
#zhihu_username:     Anderson
github_username:    Jerey-Jobs
jianshu_username:   016a5ba708a0
#twitter_username:  huxpro
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: jerey
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing
netease_comment: true



# Analytics settings
# Baidu Analytics
ba_track_id: [ecb804bab8e4c19d23ce1dd11d5d36fb]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Android Application Developer <br> <br>
                            诸葛四郎和魔鬼党, 到底谁抢到那支宝剑"
sidebar-avatar: /img/study-dog.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



#Friends
friends: [
    {
        title: "Vic",
        href: "https://github.com/JeAmoTu/"
    },{
        title: "PandaQ",
        href: "http://www.jianshu.com/u/aa53f5d59037/"
    },{
        title: "Java-Coffee",
        href: "https://github.com/Java-Coffee/"
    }
]
